

SELECT * FROM DEVELOPER.USER_V;
SELECT * FROM DEVELOPER.BIKE_V;
SELECT * FROM DEVELOPER.ORDER_V;
SELECT * FROM DEVELOPER.CART_V;

-- FUNCS AND PROCES

--пецхярпюжхъ
BEGIN
 DBMS_OUTPUT.PUT_LINE(DEVELOPER.REGISTER('VLADISLAV','LEMIASHEUSKY','OLEGOVICH','VLAD.LEMEWEGWGHOK@GMAIL.COM','12345','25-04-2004','MINSK',1));
END;
 COMMIT;

BEGIN
 DBMS_OUTPUT.PUT_LINE(DEVELOPER.REGISTER('ALEX','BRANT','OLEGOVICH','ALEX.VASTOC@GMAIL.COM','12345','18-03-2009','MINSK',1));
END;

--юбрнпхгюжхъ

BEGIN
 DBMS_OUTPUT.PUT_LINE(DEVELOPER.LOGIN('VLAD.LEMESHOK@GMAIL.COM','12345'));
END;
 COMMIT;

-- днаюбкемхе аюийю
BEGIN
 DBMS_OUTPUT.PUT_LINE(DEVELOPER.ADD_BIKE(9,'BIKE 2',199.99,1));
END;
COMMIT;

-- днаюбкемхе нохяюмхъ аюийю
BEGIN
 DBMS_OUTPUT.PUT_LINE(DEVELOPER.ADD_DESC(9,1,'BRAND NEW!','RACING','STEEL',8,20));
END;

-- днаюбкемхе нжемйх

BEGIN
 DBMS_OUTPUT.PUT_LINE(DEVELOPER.ADD_RATE(3,9,3,'BAD!',SYSTIMESTAMP));
END;

-- намнбкемхе онкэгнбюрекъ

BEGIN
    DBMS_OUTPUT.PUT_LINE(DEVELOPER.UPDATE_USER(1,'VLADDDD','LEMESH','OLG','VLAD.LEMESHOK@GMAIL.COM','12345','25-04-2004','MINSK',2));
END;

-- япедмхи пеирхмц бекняхоедю

SELECT DEVELOPER.AVG_RATE(6) AS RATE FROM DUAL;

-- сдюкемхе бекняхоедю

BEGIN
    DEVELOPER.DEL_BIKE(2,1);
END;

-- сдюкемхе нохяюмхъ

BEGIN
    DEVELOPER.DEL_DESC(8);
END;

ROLLBACK;

-- сдюкемхе нжемйх

BEGIN
    DEVELOPER.DEL_RATE(8);
END;

-- намнбкемхе нохяюмхъ

BEGIN
    DEVELOPER.UPD_DESC(1,8,'NEW NOW!','RACING','STEEL',8,20);
END;

-- намнбкемхе нжемйх

BEGIN
    DEVELOPER.UPD_RATE(8,5,4,'BAD!',SYSTIMESTAMP);
END;

-- намнбкемхе аюийю

BEGIN
    DEVELOPER.UPDATE_BIKE(1,7,'WTP TRIG',950,1);
END;


-- днаюбкемхе бекняхоедю б йнпгхмс

BEGIN
    DEVELOPER.ADD_TO_CART(2,7,35);
    COMMIT;
END;


-- нвхярйю йнпгхмш

BEGIN
    DEVELOPER.CLEAR_CART(2);
END;

-- сдюкемхе аюийю хг йнпгхмш

BEGIN
    DEVELOPER.DEL_FROM_CART();
END;

-- нтнплкемхе гюйюгю

BEGIN
    DBMS_OUTPUT.PUT_LINE(DEVELOPER.ADD_ORDER(1,SYSDATE,'IN WAY'));
    COMMIT;
END;

-- намнбкемхе гюйюгю

BEGIN
    DEVELOPER.UPDATE_ORDER(1,2,7,10,SYSDATE,'IN WAY');
END;

-- нвхярйю гюйюгнб

BEGIN
    DEVELOPER.CLEAR_ORDER();
END;

-- сдюкемхе гюйюгю

BEGIN
    DEVELOPER.DEL_ORDER(2,1);
    COMMIT;
END;

-- онксвемхе ндмни хг рюакхж

SELECT * FROM TABLE(DEVELOPER.GETUSERS());
SELECT * FROM TABLE(DEVELOPER.GETUSERBYID(2));


-- янпрхпнбйю дюммшу

SELECT * FROM TABLE(DEVELOPER.SORT_USER_BY_ID);
SELECT * FROM TABLE(DEVELOPER.SORT_USER_BY_NAME);
SELECT * FROM TABLE(DEVELOPER.SORT_USER_BY_SURNAME);
SELECT * FROM TABLE(DEVELOPER.SORT_USER_BY_BIRTH);

SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_ID());
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_NAME);
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_DESC);
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_CATEGORY);
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_TYPE);
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_MATERIAL);
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_HEIGHT);
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_SELLER);
SELECT * FROM TABLE(DEVELOPER.SORT_BIKE_BY_WEIGHT);

SELECT * FROM TABLE(DEVELOPER.SORT_ORDER_BY_ID());
SELECT * FROM TABLE(DEVELOPER.SORT_ORDER_BY_DATE());
SELECT * FROM TABLE(DEVELOPER.SORT_ORDER_BY_QNT());
SELECT * FROM TABLE(DEVELOPER.SORT_ORDER_BY_STATUS());



--  онхяй дюммшу:

SELECT * FROM TABLE(DEVELOPER.SEARCH_BIKE_BY_ID(1));
SELECT * FROM TABLE(DEVELOPER.SEARCH_BIKE_BY_NAME(''));
SELECT * FROM TABLE(DEVELOPER.SEARCH_USER_BY_ID(4));
SELECT * FROM TABLE(DEVELOPER.SEARCH_USER_BY_NAME(''));
SELECT * FROM TABLE(DEVELOPER.SEARCH_USER_BY_SURNAME('BRANT'));
SELECT * FROM TABLE(DEVELOPER.SEARCH_USER_BY_BIRTH('25-04-2004'));



-- FULL TEXT SEARCH

SELECT * FROM TABLE(DEVELOPER.CONTAINS_BIKE('WTP TRIG'));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_USER_BY_NAME('ALEX'));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_RATEMSG('BAD'));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_USER_BY_ADRESS(''));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_USER_BY_EMAIL(''));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_USER_BY_FATHERNAME(''));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_USER_BY_SURNAME(''));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_USER_BY_NAME('USER5000'));
SELECT * FROM TABLE(DEVELOPER.CONTAINS_USER_BY_NAME(''));


SELECT * FROM TABLE(DEVELOPER.CATSEARCH_TYPE('RACING'));
SELECT * FROM TABLE(DEVELOPER.CATSEARCH_MATERIAL('STEEL'));


BEGIN
    DBMS_OUTPUT.PUT_LINE(DEVELOPER.MATCH_DESC());
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE(DEVELOPER.MATCHES_RATEMSG('BAD!'));
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE(DEVELOPER.MATCHES_TYPE());
END;



