ALTER SESSION SET "_oracle_script" = TRUE; 



-- Создание табличных пространств:
/*
create tablespace PROG_TS 
    datafile 'C:\Tablecpaces\CourseWork\PROG_TS.dbf'
    size 20M
    autoextend on next 5M
    extent management local;
    
create temporary tablespace PROG_TEMP_TS
    tempfile 'C:\Tablecpaces\CourseWork\PROG_TEMP_TS.dbf'
    size 5M
    autoextend on next 3M
    extent management local;
*/
-- Создание роли ADMIN_BD

create role DB_ADMIN;

grant 
ALL PRIVILEGES
to
DB_ADMIN;

CREATE USER COURSE_DB_ADMIN IDENTIFIED BY 123;
GRANT DB_ADMIN ,SYSDBA TO COURSE_DB_ADMIN;
-- Создание роли 
create role PROGRAMMER;

grant 
CREATE TABLE,
CREATE VIEW,
CREATE PROCEDURE,
CREATE ANY INDEX,
CREATE USER,
DROP  USER,
CREATE SEQUENCE,
CREATE TRIGGER,
CREATE ROLE,
CREATE TYPE,
CREATE ANY DIRECTORY
TO
PROGRAMMER
;

-- Создание профиля безопасности
/*
CREATE PROFILE PF_PROG LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;
*/
-- Создание пользователя 

CREATE ROLE SESSION_PRIV;

GRANT 
CREATE SESSION
TO SESSION_PRIV;

CREATE USER DEVELOPER IDENTIFIED BY 12345;
GRANT SESSION_PRIV TO DEVELOPER WITH ADMIN OPTION;
GRANT PROGRAMMER TO DEVELOPER;

-- ORACLE TEXT

GRANT CTXAPP TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.DRUE  TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.TEXTINDEXMETHODS  TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_CLS TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_DDL TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_DOC TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_OUTPUT TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_QUERY TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_REPORT TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_THES TO DEVELOPER;
GRANT EXECUTE ON CTXSYS.CTX_ULEXER TO DEVELOPER;


DROP TABLESPACE PROG_TS;
DROP TABLESPACE PROG_TEMP_TS;
DROP PROFILE PF_PROG;
DROP ROLE PROGRAMMER;
DROP ROLE DB_ADMIN;
DROP USER DEVELOPER;
DROP USER COURSE_DB_ADMIN;



